### ISSUE TITLE
Update branches / tags for semver

### ISSUE THREAD

**Issue by wilr** [chewyou/algolia-search#2]
Hey @chewyou, just some thoughts to make this module easier to manage and use I suggest doing something like the following (or make me an admin, happy to do it for you!)

* Tag your current SS-4 as `2.2.0` (prior to merging #1)
* Tag your current master as `1.0.0` (I assume someone uses the SilverStripe 3 version)
* Merge the #1 PR  (it'll go into SS-4).
* Push the master branch to a `1.0` branch in case we need to support that.
* Push the SS-4 branch to `master`.

Optionally you may want to rename this repo to `silverstripe-algolia-search` to make it easier to find.

**Comment by chewyou** [comment]
Cleaned up the project a bit as suggested. More simple to manage now.
